### PR TITLE
Enable Bors and Travis

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
bors try

**Comment by nox** [comment]
bors try

**Comment by nox** [comment]
bors try

**Comment by nox** [comment]
@notriddle Am I dumb?

**Comment by nox** [comment]
bors try

**Comment by notriddle** [comment]
@nox I didn't mention it in the docs, and I'm tempted to change it, but force pushing to a branch doesn't cancel a try build, so it kept going until it finished (as you can see).

**Comment by notriddle** [comment]
You can cancel a try build by running `bors try-`, and now that I look, I should definitely add that command to the docs.

You're not dumb, by the way. I'm just not disciplined enough to make a truly great service.

**Comment by nox** [comment]
But the build was done on Travis already AFAIK so I’m not sure I understand which current build it meant.

**Comment by nox** [comment]
bors try

**Pull request merged**
